"""initial schema

Revision ID: 478127bb6eff
Revises:
Create Date: 2026-06-04 03:45:01.464048

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from app.db.base import GUID, JSONType

# revision identifiers, used by Alembic.
revision: str = "478127bb6eff"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accuracy_snapshots",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("agent_name", sa.String(length=64), nullable=False),
        sa.Column("accuracy", sa.Float(), nullable=False),
        sa.Column("calibration", sa.Float(), nullable=True),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column("weight_after", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("accuracy_snapshots", schema=None) as batch_op:
        batch_op.create_index("ix_accuracy_agent_time", ["agent_name", "created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_accuracy_snapshots_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_accuracy_snapshots_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "audit_logs",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=True),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("resource", sa.String(length=256), nullable=True),
        sa.Column("detail", JSONType(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_logs_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "connectors",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("configuration", JSONType(), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "tenant_id", name="uq_connector_name_tenant"),
    )
    with op.batch_alter_table("connectors", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_connectors_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_connectors_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "predictions",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("entity", sa.String(length=512), nullable=False),
        sa.Column("domain", sa.String(length=64), nullable=True),
        sa.Column("prediction", sa.String(length=64), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("risk_level", sa.String(length=32), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("contributors", JSONType(), nullable=True),
        sa.Column("weights_used", JSONType(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("predictions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_predictions_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_predictions_entity"), ["entity"], unique=False)
        batch_op.create_index(batch_op.f("ix_predictions_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "tenants",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("username", sa.String(length=128), nullable=False),
        sa.Column("hashed_password", sa.String(length=256), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username", "tenant_id", name="uq_user_name_tenant"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "agent_results",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("prediction_id", GUID(), nullable=False),
        sa.Column("agent_name", sa.String(length=64), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column("extra", JSONType(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["prediction_id"], ["predictions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agent_results", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_agent_results_agent_name"), ["agent_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_agent_results_prediction_id"), ["prediction_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_agent_results_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "feedback",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("prediction_id", GUID(), nullable=False),
        sa.Column("validator", sa.String(length=128), nullable=True),
        sa.Column("verdict", sa.String(length=32), nullable=False),
        sa.Column("corrected_prediction", sa.String(length=64), nullable=True),
        sa.Column("reward", sa.Float(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["prediction_id"], ["predictions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("feedback", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_feedback_prediction_id"), ["prediction_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_feedback_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "outcomes",
        sa.Column("id", GUID(), nullable=False),
        sa.Column("prediction_id", GUID(), nullable=False),
        sa.Column("actual", sa.String(length=64), nullable=False),
        sa.Column("actual_score", sa.Float(), nullable=True),
        sa.Column("correct", sa.Boolean(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(), nullable=False),
        sa.Column("tenant_id", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["prediction_id"], ["predictions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("prediction_id"),
    )
    with op.batch_alter_table("outcomes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_outcomes_tenant_id"), ["tenant_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("outcomes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_outcomes_tenant_id"))

    op.drop_table("outcomes")
    with op.batch_alter_table("feedback", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_feedback_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_feedback_prediction_id"))

    op.drop_table("feedback")
    with op.batch_alter_table("agent_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_results_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_agent_results_prediction_id"))
        batch_op.drop_index(batch_op.f("ix_agent_results_agent_name"))

    op.drop_table("agent_results")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_tenant_id"))

    op.drop_table("users")
    op.drop_table("tenants")
    with op.batch_alter_table("predictions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_predictions_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_predictions_entity"))
        batch_op.drop_index(batch_op.f("ix_predictions_created_at"))

    op.drop_table("predictions")
    with op.batch_alter_table("connectors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_connectors_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_connectors_name"))

    op.drop_table("connectors")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_created_at"))

    op.drop_table("audit_logs")
    with op.batch_alter_table("accuracy_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_accuracy_snapshots_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_accuracy_snapshots_created_at"))
        batch_op.drop_index("ix_accuracy_agent_time")

    op.drop_table("accuracy_snapshots")
    # ### end Alembic commands ###
